[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/templates/*"
  to = "/templates/:splat"
  status = 200

[[redirects]]
  from = "/previews/*"
  to = "/previews/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
